fos_rest:
    # Config the format of the response
    view:
        view_response_listener: true
        formats:
            json: true
    # Set what format we allow to received
    format_listener:
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
    # Enable the listener for the payload
    body_listener:
        enabled: true
    # Enable the param fetcher (param in the url)
    param_fetcher_listener:
        enabled: true
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
