# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    # disable _format in route list
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
        formats:
            json: true
    format_listener:
        rules:
            path: "^/"
            priorities: ["json"]
            fallback_format: "json"
            prefer_extension: true
    body_listener: true
    param_fetcher_listener: true
    exception:
        enabled: true
        exception_controller: "fos_rest.exception.controller:showAction"
