nelmio_api_doc:
    documentation:
        host: http://localhost:8000
        schemes: [http]
        info:
            title: Nabophial API
            description: Official documentation for the Nabophial API
            version: 1.2.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []

    models: { use_jms: false }

    areas: # to filter documented areas
        path_patterns:
            - ^/(?!api/doc$) # Accepts routes under / except /api/doc
