# A

App\Entity\AuthToken:
  attributes:
    id:
      groups: ['auth-token']
    value:
      groups: ['auth-token']
    createdAt:
      groups: ['auth-token']
    user:
      groups: ['auth-token']

# C

App\Entity\City:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']
    departement:
      groups: ['all']

# D

App\Entity\Departement:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']
    region:
      groups: ['all']

# E

App\Entity\Event:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']
    lieu:
      groups: ['all']
    beginTime:
      groups: ['all']
    endDate:
      groups: ['all']
    horaire:
      groups: ['all']
    nbrMax:      
      groups: ['all']
    description:
      groups: ['all']
    privateEvent:
      groups: ['all']
    status:
      groups: ['all']


# I

App\Entity\Img:
  attributes:
    id:
      groups: ['all']
    photo:
      groups: ['all']
    user:
      groups: ['all']


# P

App\Entity\Performance:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']
    typePerformance:
      groups: ['all']
    sport:
      groups: ['all']

App\Entity\Place:
  attributes:
    id:
      groups: ['all']
    positionGps:
      groups: ['all']
    adresse:
      groups: ['all']
    ville:
      groups: ['all']

# R

App\Entity\Region:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']

App\Entity\Relation:
  attributes:
    id:
      groups: ['all']
    idUser1:
      groups: ['all']
    idUser2:
      groups: ['all']
    status:
      groups: ['all']
    userAction:
      groups: ['all']

# S

App\Entity\Sport:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']

App\Entity\Status:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']

# T

App\Entity\TypePerformance:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']

# U

App\Entity\User:
  attributes:
    id:
      groups: ['all', 'auth-token']
    lastname:
      groups: ['all']
    firstname:
      groups: ['all']
    birthday:
      groups: ['all']
    email:
      groups: ['all', 'auth-token']
    number:
      groups: ['all']
    gender:
      groups: ['all']
    preference:
      groups: ['all']