
App\Entity\AuthToken:
  attributes:
    id:
      groups: ['auth-token']
    value:
      groups: ['auth-token']
    createdAt:
      groups: ['auth-token']
    user:
      groups: ['auth-token']

App\Entity\City:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']
    departement:
      groups: ['all']

App\Entity\Departement:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']
    region:
      groups: ['all']

App\Entity\Region:
  attributes:
    id:
      groups: ['all']
    name:
      groups: ['all']

App\Entity\User:
  attributes:
    id:
      groups: ['all', 'auth-token']
    lastname:
      groups: ['all']
    firstname:
      groups: ['all']
    birthday:
      groups: ['all']
    email:
      groups: ['all', 'auth-token']
    number:
      groups: ['all']
    gender:
      groups: ['all']
    preferance:
      groups: ['all']
    

